#!/bin/bash

# =========================================================================================== #
#                                                                                             #
#: Title           : SetAuto                                                                  #
#: Sypnosis        : SetAuto                                                                  #
#: Date Created    : Thu Oct 17 17:47:24 PHT 2013 / Thu Oct 17 09:48:11 UTC 2013              #
#: Last Edit       : Fri Oct 18 07:38:59 PHT 2013 / Thu Oct 17 23:39:17 UTC 2013              #
#: License         : GPLv3                                                                    #
#: Version         : 1.0                                                                      #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                               #
#: Description     : Set extradata to auto or manual of your vms.                             #
#: Options         : NONE                                                                     #
#                                                                                             #
# =========================================================================================== #

# =========================================================================================== #
#                                                                                             # 
#                                >>> START OF SCRIPT <<<                                      #
#                                                                                             #
# =========================================================================================== #

# ******************************************************************************************* #
#                                                                                             #
#                   Set shell option to have multiple test and avoid regexp.                  #
#                                                                                             #
# ******************************************************************************************* #

shopt -s extglob


# ******************************************************************************************* #
#                                                                                             #
#                                list only the vms names.                                     #
#                                                                                             #
# ******************************************************************************************* #

listvms=(
  $(
    while IFS='"' read -ra list; do
      echo "${list[1]}"
    done < <(VBoxManage list vms)
  )
)


# ******************************************************************************************* #
#                                                                                             #
#              Prints the vms with it's corresponding number within the array.                #
#                                                                                             #
# ******************************************************************************************* #

numbered(){ 
  for i in "${!listvms[@]}"; do
    printf "%s\n" "${listvms[i]/#/$i) }"
  done
}


# ******************************************************************************************* #
#                                                                                             #
#                         Function to  set all the vms to auto.                               #
#                                                                                             #
# ******************************************************************************************* #

AutoAll() {
  for all in "${listvms[@]}"; do
    VBoxManage setextradata "$all"  pvbx/startupMode auto 
  done
}


# ******************************************************************************************* #
#                                                                                             #
#                         Function to set all the vms to manual.                              #
#                                                                                             #
# ******************************************************************************************* #

ManualAll(){
  for all in "${listvms[@]}"; do
    VBoxManage setextradata "$all"  pvbx/startupMode manual
  done
}


# ******************************************************************************************* #
#                                                                                             #
#              Wait for 2 seconds so user can see the output and clear the screen.            #
#                                                                                             #
# ******************************************************************************************* #

Wait(){
  sleep 2 
  clear
}


# ******************************************************************************************* #
#                                                                                             #
#                  Get only the respective number of the vms in the array.                    #
#                                                                                             #
# ******************************************************************************************* #

num=(
  $(
     while read -r line; do
       echo "${line[@]%)*}"
     done < <(numbered)
   )
)


# ******************************************************************************************* #
#                                                                                             #
#             Format the numbers in the array so it can be tested  in one line.               #
#                                                                                             #
# ******************************************************************************************* #

printf -v new "%s|" "@(${num[@]})"
new=${new%%|} 


# ******************************************************************************************* #
#                                                                                             #
#                        The main menu when the script started.                               #
#                                                                                             #
# ******************************************************************************************* #

MainMenu(){
  cat <<-EOF
+=========================================+
|  What do you want to do with the vms?   |
+=========================================+

1) Set to Auto.
2) Set to Manual.
Q) Exit.

=>

EOF

}


# ******************************************************************************************* #
#                                                                                             #
#                                      The submenu.                                           #
#                                                                                             #
# ******************************************************************************************* #

SubMenu() {
  cat <<-EOF
+===========================================+
|     Key in  the number of the vms.        |
+===========================================+ 

$(numbered)
A) All vms
R) Return to main menu.
Q) Exit.

=>

EOF

}


# ******************************************************************************************* #
#                                                                                             #
#          Check if vms is more than 9, if it is then one click button is diabled.            #
#                                                                                             #
# ******************************************************************************************* #

VmsTotal() {
  if (( ${#listvms[@]} < 10  )); then
    read -r -e -p "$sub_menu" -n1
  elif (( ${#listvms[@]} > 9 )); then
    read -r -e -p "$sub_menu" 
  fi
}


# ******************************************************************************************* #
#                                                                                             #
#                Save the Menu's to a variable so read can present it properly.               #
#                                                                                             #
# ******************************************************************************************* #

printf -v main_menu "%s" "$(MainMenu) "
printf -v sub_menu "%s" "$(SubMenu) "


# ******************************************************************************************* #
#                                                                                             #
#                               Function to set vms to auto.                                  #
#                                                                                             #
# ******************************************************************************************* #

Auto() {
  clear
  while true; do
    VmsTotal
     if  [[ ${REPLY} = $new ]]; then   
       VBoxManage setextradata "${listvms[${REPLY}]}"  pvbx/startupMode auto
       printf "\n%s " "${listvms[${REPLY}]} has been set to auto."
       Wait
     elif [[ ${REPLY} = [Aa] ]]; then
       AutoAll
       printf "\n%s " "${listvms[*]} has been set to auto."
       Wait
     elif [[ ${REPLY} = [Rr] ]]; then
       return 0
     elif [[ ${REPLY} = [Qq] ]]; then
       clear
       exit 0
     else  
       printf "\n%s" "Invalid option!" >&2
       Wait
     fi
  done
}


# ******************************************************************************************* #
#                                                                                             #
#                                 Function to set vms to manual.                              #
#                                                                                             #
# ******************************************************************************************* #

Manual(){
  clear
  while true; do   
    VmsTotal
      if  [[ ${REPLY} = $new ]]; then
        VBoxManage setextradata "${listvms[${REPLY}]}"  pvbx/startupMode manual
        printf "\n%s " "${listvms[${REPLY}]} has been set to manual."
        Wait
      elif [[ ${REPLY} = [Aa] ]]; then
        ManualAll 
        printf "\n%s " "${listvms[*]} has been set to manual."
        Wait
      elif [[ ${REPLY} = [Rr] ]]; then
        return 0    
        clear
      elif [[ ${REPLY} = [Qq] ]]; then
        clear
        exit 0    
      else
        printf "\n%s" "Invalid option!" >&2
        Wait
       fi
  done
}


# ******************************************************************************************* #
#                                                                                             #
#                                  Parsing the main menu.                                     #
#                                                                                             #
# ******************************************************************************************* #

while true; do
  clear
  read -r -e -p "$main_menu" -n1
    case ${REPLY} in 
       1) Auto  ;;
       2) Manual
          clear ;;
    [Qq]) clear
          exit 0;;
       *) printf "\n%s" "Invalid option!" >&2
          Wait
          clear ;;
    esac
done


# ******************************************************************************************** #
#                                                                                              #
#                                   Set the exit staus.                                        #
#                                                                                              #
# ******************************************************************************************** #

exit 0


# ============================================================================================ #
#                                                                                              # 
#                                  >>> END OF SCRIPT <<<                                       #
#                                                                                              #
# ============================================================================================ #
