.\" Manpage for systemd-vboxinit
.\" Contact jetchisel@opensuse.org to correct errors or typos.
.TH SYSTEMD-VBOXINIT 1 "27 Oct 2013" "1.0" "systemd-vboxinit man page"
.SH NAME
systemd-vboxinit - auto start/save of vbox vms during boot and shutdown.
.SH SYNOPSIS
systemd-vboxinit {start|stop}
.SH DESCRIPTION
Systemd-vboxinit is wrapper script that manage VirtualBox's vms to auto start and auto save in batch. 
Derived from "vboxinit" which came from the phpvirtualbox project which is based on vboxtool. It is
then used for the legacy system V startup daemon. This is the modified/rewritten version for OpenSuSE
with systemd as it's startup daemon. ( which should work for other distro that is using systemd ).

.SH MANAGE VMS

At creation time of the vms the extradata with the key pvbx/startupMode has no value.(Which is ignored)
One need's to add the "auto" flag to the virtual machine in order for it  auto boot and auto save during 
startup and shutdown or reboot of the host. The virtual machines are then run in the background.
(which is what a daemon is all about :-)). One can access the virtual machines by using ssh(1) or with the 
gui tools such as  Krdc for KDE and the equivalent for other DE's. Example of commands are:

List the vms.

  VBoxManage list vms

Set the "auto" flag to the vms.

  VBoxManage setextradata vm-name pvbx/startupMode auto

Set the "manual" flag to the vms.
 
  VBoxManage setextradata vm_name pvbx/startupMode manual
 
Where "vm_name" is the name of the virtual machine.

.SH NOTE
 
It is not recommended to run the script with root's right such as running it with the all time favorite sudo utility.
Once one have set the "auto" flag to the virtual machines one can test the script. Invoke it as a normal
user that belongs to the vboxusers group. (It should be in once PATH so absolute path is not necessary.)

 systemd-vboxinit start

 systemd-vboxinit stop

One should see the virtual machines starting and saving state. If that succeeded one can enable the daemon and reboot.

.SH USING THE DAEMON 

Start the service.

  systemctl start VBoxAutostart@foo  

Enable the service.

  systemctl enable VBoxAutostart@foo

Check the status of the service

  systemctl status VBoxAutostart@foo

  journalctl _SYSTEMD_UNIT=VBoxAutostart@foo.service

Restart the service.

  systemctl restart VBoxAutostart@foo
  
Where foo is the username of the user who will use systemd-vboxinit.

.SH DOCS

/usr/share/doc/packages/systemd-vboxinit

.SH SEE ALSO

systemctl(1), systemd(1), systemd.unit(5), systemd.service(5), VBoxManage

.SH AUTHOR

Jason V. Ferrer (jetchisel@opensuse.org)
 
