#!/bin/bash

# =========================================================================================== #
#: Title           : systemd-vboxinit                                                         #
#: Sypnosis        : systemd-vboxinit [OPTIONS]                                               #
#: Date Created    : Wed Oct  2 07:57:25 PHT 2013                                             #
#: Last Edit       : Fri Dec 20 15:48:41 PHT 2013 / Fri Dec 20 07:49:17 UTC 2013              #
#: License         : GPLv3                                                                    #
#: Version         : 1.5                                                                      #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                               #
#: Description     : Auto start sessions when booting and save sessions when host is stopped. #
#: Options         : {stop|start}                                                             #
# =========================================================================================== #

# ******************************************************************************************* #
#                                                                                             #
#              Check if VirtualBox is installed if not exit with an error.                    #
#                                                                                             #
# ******************************************************************************************* #

if ! type -P VirtualBox >/dev/null 2>&1; then
  if ! type -P virtualbox >/dev/null 2>&1; then
    echo "VirtualBox is either not installed or is not in your PATH." >&2
    exit 1
  fi
fi

# ******************************************************************************************* #
#                                                                                             #
#                                  VBoxManage Functions.                                      #
#                                                                                             #
# ******************************************************************************************* #

ListVms() {
  VBoxManage list vms
}

RunningVms() { 
   while read -r vm; do
    uuid=${vm##*"{"} 
    echo "${uuid%"}"*}"
  done < <(VBoxManage list runningvms) 
}

ExtraData() {
  VBoxManage getextradata "$uuid" 'pvbx/startupMode'
}

StartVms() {
  VBoxManage startvm "$uuid" --type headless
}

SaveVms() {
  VBoxManage controlvm "$uuid" savestate
}

# ******************************************************************************************* #
#                                                                                             #
#                          Function to start the vms Headless.                                # 
#                                                                                             #
# ******************************************************************************************* #

start() {
  while read -r line; do 
    uuid=${line##*"{"}
    uuid=${uuid%"}"*}
    Vmname=${line#*\"}
    Vmname=${Vmname%%\"*}
  
    if [[ $(ExtraData) = *auto* ]]; then
      if ! grep -q "${uuid}" < <(RunningVms); then
        printf '\n%s\n' "Starting Machine '$Vmname'..."
        StartVms
      else 
        printf '\n%s\n' "Machine '$Vmname' is already running..."
      fi
    elif [[ $(ExtraData) != *auto* ]]; then
      printf '\n%s\n' "Machine '$Vmname' is not set to auto...."
    fi 
  done < <(ListVms) 
}

# ******************************************************************************************* #
#                                                                                             #
#              Function to save vms state instead of shutting down completely.                #
#                                                                                             #
# ******************************************************************************************* #

stop() {
   while read -r line; do 
     uuid=${line##*"{"}
     uuid=${uuid%"}"*}
     Vmname=${line#*\"}
     Vmname=${Vmname%%\"*} 
     
     if grep -q "${uuid}" < <(RunningVms); then
       printf '\n%s\n' "Saving machine '$Vmname' state..."
       SaveVms
     fi
  done < <(ListVms)
}

# ******************************************************************************************** #
#                                                                                              #
#                              Check for a command line options.                               #
#                                                                                              #
# ******************************************************************************************** #

case $1 in
  stop|start) "$1" ;;              
           *) echo 'Usage {start|stop}' ;;
esac

# ******************************************************************************************** #
#                                                                                              #
#                                   Set the exit staus.                                        #
#                                                                                              #
# ******************************************************************************************** #

exit 0

# ============================================================================================ #
#                                                                                              #
#                                  >>> END OF SCRIPT <<<                                       #
#                                                                                              #
# ============================================================================================ #
